// Lazy-load a Google Font family at runtime by injecting a <link> into <head>.
// De-duplicates: each family is loaded at most once per page session.

const loaded = new Set();

const familyToUrl = (family, weights = '400;500;600;700') =>
  `https://fonts.googleapis.com/css2?family=${family.replace(/\s+/g, '+')}:wght@${weights}&display=swap`;

export function ensureGoogleFont(family) {
  if (!family || loaded.has(family)) return;
  loaded.add(family);
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = familyToUrl(family);
  link.dataset.googleFont = family;
  document.head.appendChild(link);
}

// Bulk: ensure many families are loaded (used by the picker for live previews).
export function ensureGoogleFonts(families) {
  families.forEach(ensureGoogleFont);
}

// A curated catalog of popular Google Fonts that appear in the "More fonts..."
// picker. Not exhaustive — covers ~250 widely-used families across categories.
// Each entry: [family, category]. The family must match Google Fonts spelling
// exactly so the css2 URL resolves.
export const GOOGLE_FONTS_CATALOG = [
  // ─ Sans-serif ─────────────────────────────────────────────────────────────
  ['ABeeZee', 'sans'],
  ['Albert Sans', 'sans'],
  ['Alegreya Sans', 'sans'],
  ['Alexandria', 'sans'],
  ['Anek Latin', 'sans'],
  ['Antonio', 'sans'],
  ['Archivo', 'sans'],
  ['Archivo Narrow', 'sans'],
  ['Asap', 'sans'],
  ['Assistant', 'sans'],
  ['Average Sans', 'sans'],
  ['Be Vietnam Pro', 'sans'],
  ['BioRhyme', 'sans'],
  ['Cabin', 'sans'],
  ['Cairo', 'sans'],
  ['Carlito', 'sans'],
  ['Catamaran', 'sans'],
  ['Chakra Petch', 'sans'],
  ['Chivo', 'sans'],
  ['Comfortaa', 'sans'],
  ['Commissioner', 'sans'],
  ['Darker Grotesque', 'sans'],
  ['DM Sans', 'sans'],
  ['Dosis', 'sans'],
  ['Encode Sans', 'sans'],
  ['Epilogue', 'sans'],
  ['Familjen Grotesk', 'sans'],
  ['Faustina', 'sans'],
  ['Figtree', 'sans'],
  ['Fira Sans', 'sans'],
  ['Frank Ruhl Libre', 'sans'],
  ['Geologica', 'sans'],
  ['Geist', 'sans'],
  ['Golos Text', 'sans'],
  ['Heebo', 'sans'],
  ['Hind', 'sans'],
  ['Hind Madurai', 'sans'],
  ['Host Grotesk', 'sans'],
  ['IBM Plex Sans', 'sans'],
  ['Inclusive Sans', 'sans'],
  ['Instrument Sans', 'sans'],
  ['Inter', 'sans'],
  ['Inter Tight', 'sans'],
  ['Josefin Sans', 'sans'],
  ['Jost', 'sans'],
  ['Kanit', 'sans'],
  ['Karla', 'sans'],
  ['Kumbh Sans', 'sans'],
  ['Lato', 'sans'],
  ['Lexend', 'sans'],
  ['Libre Franklin', 'sans'],
  ['M PLUS Rounded 1c', 'sans'],
  ['Manrope', 'sans'],
  ['Maven Pro', 'sans'],
  ['Merriweather Sans', 'sans'],
  ['Montserrat', 'sans'],
  ['Mukta', 'sans'],
  ['Mulish', 'sans'],
  ['Noto Sans', 'sans'],
  ['Nunito', 'sans'],
  ['Nunito Sans', 'sans'],
  ['Onest', 'sans'],
  ['Open Sans', 'sans'],
  ['Outfit', 'sans'],
  ['Overpass', 'sans'],
  ['Oxanium', 'sans'],
  ['Plus Jakarta Sans', 'sans'],
  ['Poppins', 'sans'],
  ['Prompt', 'sans'],
  ['PT Sans', 'sans'],
  ['Public Sans', 'sans'],
  ['Questrial', 'sans'],
  ['Quicksand', 'sans'],
  ['Raleway', 'sans'],
  ['Readex Pro', 'sans'],
  ['Roboto', 'sans'],
  ['Roboto Condensed', 'sans'],
  ['Roboto Flex', 'sans'],
  ['Rubik', 'sans'],
  ['Saira', 'sans'],
  ['Schibsted Grotesk', 'sans'],
  ['Sora', 'sans'],
  ['Source Sans 3', 'sans'],
  ['Space Grotesk', 'sans'],
  ['Sulphur Point', 'sans'],
  ['Syne', 'sans'],
  ['Tajawal', 'sans'],
  ['Tilt Neon', 'sans'],
  ['Titillium Web', 'sans'],
  ['Ubuntu', 'sans'],
  ['Urbanist', 'sans'],
  ['Varela Round', 'sans'],
  ['Wix Madefor Text', 'sans'],
  ['Work Sans', 'sans'],
  ['Yantramanav', 'sans'],

  // ─ Serif ──────────────────────────────────────────────────────────────────
  ['Alegreya', 'serif'],
  ['Alegreya SC', 'serif'],
  ['Arvo', 'serif'],
  ['Bitter', 'serif'],
  ['Bree Serif', 'serif'],
  ['Cardo', 'serif'],
  ['Cormorant', 'serif'],
  ['Cormorant Garamond', 'serif'],
  ['Crimson Pro', 'serif'],
  ['Crimson Text', 'serif'],
  ['DM Serif Display', 'serif'],
  ['DM Serif Text', 'serif'],
  ['EB Garamond', 'serif'],
  ['Fraunces', 'serif'],
  ['Gentium Plus', 'serif'],
  ['IBM Plex Serif', 'serif'],
  ['Instrument Serif', 'serif'],
  ['Libre Baskerville', 'serif'],
  ['Libre Caslon Text', 'serif'],
  ['Lora', 'serif'],
  ['Marcellus', 'serif'],
  ['Merriweather', 'serif'],
  ['Neuton', 'serif'],
  ['Newsreader', 'serif'],
  ['Noticia Text', 'serif'],
  ['Noto Serif', 'serif'],
  ['Old Standard TT', 'serif'],
  ['Petrona', 'serif'],
  ['Piazzolla', 'serif'],
  ['Playfair', 'serif'],
  ['Playfair Display', 'serif'],
  ['Prata', 'serif'],
  ['PT Serif', 'serif'],
  ['Roboto Serif', 'serif'],
  ['Roboto Slab', 'serif'],
  ['Source Serif 4', 'serif'],
  ['Spectral', 'serif'],
  ['Taviraj', 'serif'],
  ['Tinos', 'serif'],
  ['Vollkorn', 'serif'],
  ['Young Serif', 'serif'],
  ['Zilla Slab', 'serif'],

  // ─ Display ────────────────────────────────────────────────────────────────
  ['Abril Fatface', 'display'],
  ['Alfa Slab One', 'display'],
  ['Anton', 'display'],
  ['Archivo Black', 'display'],
  ['Arsenal SC', 'display'],
  ['Bebas Neue', 'display'],
  ['Black Ops One', 'display'],
  ['Bowlby One', 'display'],
  ['Bungee', 'display'],
  ['Bungee Shade', 'display'],
  ['Carter One', 'display'],
  ['Caveat', 'display'],
  ['Caveat Brush', 'display'],
  ['Changa One', 'display'],
  ['Chango', 'display'],
  ['Cherry Bomb One', 'display'],
  ['Concert One', 'display'],
  ['Damion', 'display'],
  ['Dancing Script', 'display'],
  ['Diplomata', 'display'],
  ['Faster One', 'display'],
  ['Fjalla One', 'display'],
  ['Fredoka', 'display'],
  ['Gloock', 'display'],
  ['Honk', 'display'],
  ['Italianno', 'display'],
  ['Knewave', 'display'],
  ['Krona One', 'display'],
  ['Lemon', 'display'],
  ['Lilita One', 'display'],
  ['Lobster', 'display'],
  ['Lobster Two', 'display'],
  ['Lugrasimo', 'display'],
  ['Major Mono Display', 'display'],
  ['Monoton', 'display'],
  ['Nabla', 'display'],
  ['Noto Serif Display', 'display'],
  ['Oranienbaum', 'display'],
  ['Orbitron', 'display'],
  ['Pacifico', 'display'],
  ['Passion One', 'display'],
  ['Permanent Marker', 'display'],
  ['Plaster', 'display'],
  ['Playfair Display SC', 'display'],
  ['Press Start 2P', 'display'],
  ['Racing Sans One', 'display'],
  ['Rampart One', 'display'],
  ['Righteous', 'display'],
  ['Rubik Mono One', 'display'],
  ['Russo One', 'display'],
  ['Sacramento', 'display'],
  ['Satisfy', 'display'],
  ['Shrikhand', 'display'],
  ['Silkscreen', 'display'],
  ['Six Caps', 'display'],
  ['Special Elite', 'display'],
  ['Squada One', 'display'],
  ['Staatliches', 'display'],
  ['Stalemate', 'display'],
  ['Stick No Bills', 'display'],
  ['Tilt Prism', 'display'],
  ['Tilt Warp', 'display'],
  ['Ultra', 'display'],
  ['Unica One', 'display'],
  ['Yeseva One', 'display'],
  ['Yusei Magic', 'display'],

  // ─ Monospace ──────────────────────────────────────────────────────────────
  ['Anonymous Pro', 'mono'],
  ['Azeret Mono', 'mono'],
  ['B612 Mono', 'mono'],
  ['Cousine', 'mono'],
  ['Cutive Mono', 'mono'],
  ['DM Mono', 'mono'],
  ['Fira Code', 'mono'],
  ['Fira Mono', 'mono'],
  ['Geist Mono', 'mono'],
  ['IBM Plex Mono', 'mono'],
  ['Inconsolata', 'mono'],
  ['JetBrains Mono', 'mono'],
  ['Kode Mono', 'mono'],
  ['Major Mono Display', 'mono'],
  ['Martian Mono', 'mono'],
  ['Noto Sans Mono', 'mono'],
  ['Nova Mono', 'mono'],
  ['PT Mono', 'mono'],
  ['Roboto Mono', 'mono'],
  ['Share Tech Mono', 'mono'],
  ['Source Code Pro', 'mono'],
  ['Space Mono', 'mono'],
  ['Spline Sans Mono', 'mono'],
  ['Syne Mono', 'mono'],
  ['Ubuntu Mono', 'mono'],
  ['VT323', 'mono'],
  ['Xanh Mono', 'mono'],
];

export function categoryFallback(category) {
  if (category === 'serif') return 'serif';
  if (category === 'mono') return 'monospace';
  if (category === 'display') return 'sans-serif';
  return 'sans-serif';
}

// Build a font-family stack string suitable for a CSS style attribute.
export function buildStack(family, category) {
  return `'${family}', ${categoryFallback(category)}`;
}
