const p = (text = '') => ({
  type: 'paragraph',
  content: text ? [{ type: 'text', text, styles: {} }] : [],
});

const h = (text, level = 1) => ({
  type: 'heading',
  props: { level },
  content: [{ type: 'text', text, styles: {} }],
});

const bullet = (text) => ({
  type: 'bulletListItem',
  content: [{ type: 'text', text, styles: {} }],
});

const check = (text, checked = false) => ({
  type: 'checkListItem',
  props: { checked },
  content: [{ type: 'text', text, styles: {} }],
});

export const TEMPLATES = [
  {
    id: 'pentest',
    name: 'Pentest Report',
    icon: '🔴',
    description: 'Structured penetration testing report',
    blocks: [
      h('Executive Summary'),
      p('Brief overview of the engagement, scope, and key findings.'),
      h('Scope', 2),
      bullet('In-scope targets:'),
      bullet('Out-of-scope:'),
      p(),
      h('Methodology', 2),
      bullet('Reconnaissance'),
      bullet('Enumeration'),
      bullet('Exploitation'),
      bullet('Post-exploitation'),
      bullet('Reporting'),
      p(),
      h('Findings', 2),
      h('Critical', 3),
      p('No critical findings.'),
      h('High', 3),
      p(''),
      h('Medium', 3),
      p(''),
      h('Low / Informational', 3),
      p(''),
      h('Remediation Summary', 2),
      p(''),
      h('Conclusion', 2),
      p(''),
    ],
  },
  {
    id: 'ctf',
    name: 'CTF Writeup',
    icon: '🏴',
    description: 'Capture the Flag challenge writeup',
    blocks: [
      h('Challenge Info'),
      bullet('Category: '),
      bullet('Points: '),
      bullet('Difficulty: '),
      bullet('Description: '),
      p(),
      h('Initial Analysis', 2),
      p(''),
      h('Approach', 2),
      p(''),
      h('Solution', 2),
      p('Step-by-step walkthrough of the solution.'),
      p(),
      h('Flag', 2),
      p('flag{...}'),
      p(),
      h('Takeaways', 2),
      p(''),
    ],
  },
  {
    id: 'threat-model',
    name: 'Threat Model',
    icon: '🧠',
    description: 'STRIDE-based threat modeling template',
    blocks: [
      h('System Overview'),
      p('Describe the system, components, and trust boundaries.'),
      p(),
      h('Assets', 2),
      bullet(''),
      p(),
      h('Threat Analysis (STRIDE)', 2),
      h('Spoofing', 3),
      p(''),
      h('Tampering', 3),
      p(''),
      h('Repudiation', 3),
      p(''),
      h('Information Disclosure', 3),
      p(''),
      h('Denial of Service', 3),
      p(''),
      h('Elevation of Privilege', 3),
      p(''),
      h('Mitigations', 2),
      p(''),
      h('Risk Rating', 2),
      p(''),
    ],
  },
  {
    id: 'technique',
    name: 'Technique Notes',
    icon: '🛡️',
    description: 'Document an attack technique or TTP',
    blocks: [
      h('Overview'),
      p(''),
      h('MITRE ATT&CK', 2),
      bullet('Tactic: '),
      bullet('Technique ID: '),
      bullet('Platform: '),
      p(),
      h('Prerequisites', 2),
      bullet(''),
      p(),
      h('Steps', 2),
      p(''),
      h('Detection', 2),
      p(''),
      h('References', 2),
      bullet(''),
    ],
  },
  {
    id: 'meeting',
    name: 'Meeting Notes',
    icon: '📋',
    description: 'Standard meeting notes template',
    blocks: [
      h('Meeting Details'),
      bullet('Date: '),
      bullet('Attendees: '),
      bullet('Facilitator: '),
      p(),
      h('Agenda', 2),
      check(''),
      check(''),
      p(),
      h('Notes', 2),
      p(''),
      h('Action Items', 2),
      check(''),
      check(''),
    ],
  },
  {
    id: 'bug-report',
    name: 'Bug Report',
    icon: '🐛',
    description: 'Structured vulnerability or bug report',
    blocks: [
      h('Summary'),
      p('One-line description of the bug.'),
      p(),
      h('Severity', 2),
      p('Critical / High / Medium / Low'),
      p(),
      h('Steps to Reproduce', 2),
      p('1. '),
      p('2. '),
      p('3. '),
      p(),
      h('Expected Behavior', 2),
      p(''),
      h('Actual Behavior', 2),
      p(''),
      h('Impact', 2),
      p(''),
      h('Proof of Concept', 2),
      p(''),
      h('Remediation', 2),
      p(''),
    ],
  },
];
